{
    'name': 'LTD Infra — Gestión de Presupuestos de Construcción',
    'version': '18.0.3.1.0',
    'category': 'Construction',
    'summary': 'Presupuestos de licitación para obras de infraestructura vial',
    'author': 'Latigid',
    'website': 'https://github.com/misaelgemio/ltd_infra',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'product', 'purchase', 'stock', 'web', 'project'],
    'data': [
        'security/infra_security.xml',
        'security/ir.model.access.csv',
        'data/infra_product_categories.xml',
        'data/infra_configuracion_data.xml',
        'data/infra_productos_b3.xml',
        'data/infra_apu_data.xml',
        'views/product_template_views.xml',
        'views/infra_configuracion_views.xml',
        'views/infra_project_views.xml',
        'views/infra_tramo_views.xml',
        'views/infra_item_obra_views.xml',
        'views/infra_apu_views.xml',
        'views/infra_cronograma_views.xml',
        'data/infra_b4_b9_data.xml',
        'data/infra_beni_data.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
}
